# Generated by Django 3.0.1 on 2020-01-26 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_emg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='emg',
        ),
        migrations.RenameField(
            model_name='friendvisitor',
            old_name='role',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='friendvisitor',
            name='image',
        ),
    ]
