# Generated by Django 3.0.1 on 2020-01-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_auto_20200126_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendvisitor',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
