# Generated by Django 3.0.1 on 2020-01-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_auto_20200126_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expectedvisitor',
            name='user',
        ),
        migrations.DeleteModel(
            name='otp',
        ),
        migrations.AddField(
            model_name='friendvisitor',
            name='Type',
            field=models.CharField(blank=True, choices=[('Bag', 'Bag'), ('Bin', 'Bin'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='friendvisitor',
            name='location',
            field=models.CharField(blank=True, default='vijay', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='friendvisitor',
            name='phone',
            field=models.CharField(blank=True, default='5756798953', max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='expectedvisitor',
        ),
    ]
