# Generated by Django 3.0.1 on 2020-01-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_auto_20200126_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendvisitor',
            name='unit',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
    ]
