# Generated by Django 3.0.1 on 2020-01-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_friendvisitor_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendvisitor',
            name='status',
            field=models.CharField(blank=True, choices=[('allow', 'Allow'), ('pending', 'Pending')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='friendvisitor',
            name='unit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
