# Generated by Django 3.0.1 on 2020-01-27 17:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0031_auto_20200126_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='urgentvis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, default='5756798953', max_length=10, null=True)),
                ('Location', models.CharField(blank=True, choices=[('Area A', 'Area A'), ('Area B', 'Area B'), ('Area C', 'Area C')], max_length=50, null=True)),
                ('Type', models.CharField(blank=True, choices=[('Bag', 'Bag'), ('Bin', 'Bin'), ('Other', 'Other')], max_length=50, null=True)),
                ('unit', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.CharField(blank=True, choices=[('allow', 'Allow'), ('pending', 'Pending')], default='pending', max_length=50)),
                ('user', models.ForeignKey(default='vijay', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
