# Generated by Django 3.0.1 on 2020-01-27 17:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0032_urgentvis'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='urgentvis',
            new_name='urgentvisitor',
        ),
    ]
