# Generated by Django 3.0.1 on 2020-01-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_auto_20200127_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendvisitor',
            name='reward',
            field=models.CharField(blank=True, choices=[('paid', 'paid'), ('not paid', 'not paid')], default='not paid', max_length=50),
        ),
        migrations.AlterField(
            model_name='friendvisitor',
            name='status',
            field=models.CharField(blank=True, choices=[('paid', 'paid'), ('not paid', 'not paid')], default='pending', max_length=50),
        ),
    ]
