# Generated by Django 3.0.1 on 2020-01-27 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_auto_20200128_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='urgentvisitor',
            name='response',
            field=models.CharField(blank=True, choices=[('not collected', 'not collected'), ('collected', 'collected')], default='not collected', max_length=50),
        ),
        migrations.AddField(
            model_name='urgentvisitor',
            name='reward',
            field=models.CharField(blank=True, choices=[('paid', 'paid'), ('not paid', 'not paid')], default='not paid', max_length=50),
        ),
    ]
